/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.Client;
import Backend.Part;
import Backend.Sale;
import Backend.clientManager;
import Backend.inventoryManager;
import Backend.saleManager;
import DBMS.DB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dazzl
 */
public class clientEditor extends javax.swing.JFrame {

    // The global variables that are required for fulling in the data on this screen.
    private Part part;
    private inventoryManager manager;

    /**
     * Creates new form editPanel
     */
    //Building site
    public clientEditor() {
        initComponents();
        
        int clientID = Integer.parseInt(JOptionPane.showInputDialog("Please enter your client number"));
        // This method populates the UI components with the data from the class
        populateFields(clientID);
        populateSalesTable(clientID);
        
        // Disposes the screen on close but not the whole prgram
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Populates the combo box with the correct fields which can be selected for a part

        
        //Places the screen in the middle of the users display
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editItemHeader = new javax.swing.JLabel();
        enterNameTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        loyaltyStatusButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        totalSpentJSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientPurchasesJTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editItemHeader.setFont(new java.awt.Font("Candara Light", 0, 48)); // NOI18N
        editItemHeader.setText("EDIT CLIENT");

        enterNameTextField.setText("Enter your name...");
        enterNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterNameTextFieldActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        priceLabel.setText("LOYALTY");

        confirmButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        loyaltyStatusButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        loyaltyStatusButton.setText("LOYALTY");

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setText("Total Spent:");

        clientPurchasesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(clientPurchasesJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(enterNameTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loyaltyStatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalSpentJSpinner)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editItemHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(editItemHeader)
                .addGap(30, 30, 30)
                .addComponent(enterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loyaltyStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalSpentJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Enetering the name of the part
    private void enterNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterNameTextFieldActionPerformed

    }//GEN-LAST:event_enterNameTextFieldActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed

    }//GEN-LAST:event_confirmButtonActionPerformed
    
    // The metod which fills in the data of the UI components
        private void populateFields(int inCID) {
            clientManager cManager = new clientManager();
            if(cManager.findClientById(inCID) == null){
                JOptionPane.showMessageDialog(null, "Client not found", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                Client c = cManager.findClientById(inCID);
                enterNameTextField.setText(c.getName());
                
                if(c.isLoyalty() == true){
                    loyaltyStatusButton.setSelected(true);
                }
                else{
                    loyaltyStatusButton.setSelected(false);
                }
                
                totalSpentJSpinner.setValue(c.getTotalSpent());
                
                    
                

            }
        }
            
 private void populateSalesTable(int clientID) {

    saleManager manager = new saleManager();

    DefaultTableModel tableModel = new DefaultTableModel();


    tableModel.addColumn("Sale ID");
    tableModel.addColumn("Total");

    ArrayList<Sale> salesMadeByClient = manager.findSalesById(clientID);

    for (Sale sale : salesMadeByClient) {
        Object[] rowData = {
            sale.getSaleID(),   
            sale.getTotal()    
        };
        

        tableModel.addRow(rowData);
    }

    clientPurchasesJTable.setModel(tableModel);
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientPurchasesJTable;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel editItemHeader;
    private javax.swing.JTextField enterNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton loyaltyStatusButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JSpinner totalSpentJSpinner;
    // End of variables declaration//GEN-END:variables
}
