/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.Client;
import Backend.Part;
import Backend.Sale;
import Backend.clientManager;
import Backend.inventoryManager;
import Backend.saleManager;
import DBMS.DB;
import UI.SaleDetailsPanel;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dazzl
 */
public class ClientEditPanel extends javax.swing.JFrame {

    // The global variables that are required for fulling in the data on this screen.
    private Part part;
    private inventoryManager inventoryManager;
    private clientManager cManager;
    private saleManager saleManager;
    private int clientID;

    /**
     * Creates new form editPanel
     */
    public ClientEditPanel() {
        //Initializes the UI components
        initComponents();
        
        //Creates the required managers for the data
        this.cManager = new clientManager();
        this.inventoryManager = new inventoryManager();
        this.saleManager = new saleManager();
        
        this.clientID = Integer.parseInt(JOptionPane.showInputDialog("Please enter your client number"));
        
        //This method populates the UI components with the data from the class
        populateFields(clientID);
        populateSalesTable(clientID);
        
        // Disposes the screen on close but not the whole prgram
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Populates the combo box with the correct fields which can be selected for a part

        
        //Places the screen in the middle of the users display
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editItemHeader = new javax.swing.JLabel();
        enterNameTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        loyaltyStatusButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        totalSpentJSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientPurchasesJTable = new javax.swing.JTable();
        saleContentsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(7, 132, 181));

        editItemHeader.setFont(new java.awt.Font("Candara Light", 0, 48)); // NOI18N
        editItemHeader.setText("VIEW CLIENT");

        enterNameTextField.setText("Enter your name...");
        enterNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterNameTextFieldActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        priceLabel.setText("LOYALTY");

        confirmButton.setBackground(new java.awt.Color(202, 222, 239));
        confirmButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(7, 132, 181));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        loyaltyStatusButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        loyaltyStatusButton.setText("LOYALTY");
        loyaltyStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loyaltyStatusButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setText("Total Spent:");

        clientPurchasesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(clientPurchasesJTable);

        saleContentsButton.setBackground(new java.awt.Color(202, 222, 239));
        saleContentsButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        saleContentsButton.setForeground(new java.awt.Color(7, 132, 181));
        saleContentsButton.setText("VIEW");
        saleContentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleContentsButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("CLIENT NAME:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(loyaltyStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalSpentJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saleContentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(enterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editItemHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(editItemHeader)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loyaltyStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalSpentJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(saleContentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterNameTextFieldActionPerformed

    }//GEN-LAST:event_enterNameTextFieldActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void saleContentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleContentsButtonActionPerformed
        int selectedRow = clientPurchasesJTable.getSelectedRow();
        
        int inSID = Integer.parseInt(clientPurchasesJTable.getValueAt(selectedRow, 0).toString());
        
        SaleDetailsPanel salePanelInstance = new SaleDetailsPanel(inSID);
        salePanelInstance.setVisible(true);
    }//GEN-LAST:event_saleContentsButtonActionPerformed

    private void loyaltyStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loyaltyStatusButtonActionPerformed
        boolean isSelected = loyaltyStatusButton.isSelected();
        
        //IE does have royalty, removing royalty status
        if(isSelected == false){
            loyaltyStatusButton.setBackground(Color.red);
            loyaltyStatusButton.setSelected(isSelected);
            
        }
        //IE doesn't have royalty, giving the client royalty status
        else if(isSelected == true){
            loyaltyStatusButton.setBackground(Color.green);
            loyaltyStatusButton.setSelected(isSelected);
        }
        
        cManager.setLoyalty(isSelected, clientID);
    }//GEN-LAST:event_loyaltyStatusButtonActionPerformed
    
    // The metod which fills in the data of the UI components
        private void populateFields(int inCID) {
            
            if(cManager.findClientById(inCID) == null){
                JOptionPane.showMessageDialog(null, "Client not found", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                Client c = cManager.findClientById(inCID);
                enterNameTextField.setText(c.getName());
                
                
                //The problem with this is that the Client obkect doesn't update
                if(c.isLoyalty() == true){
                    loyaltyStatusButton.setSelected(true);
                    loyaltyStatusButton.setBackground(Color.green);
                }
                else{
                    loyaltyStatusButton.setSelected(false);
                    loyaltyStatusButton.setBackground(Color.red);
                }
                
                totalSpentJSpinner.setValue(c.getTotalSpent());
                
                    
                

            }
        }
            
 private void populateSalesTable(int clientID) {

    DefaultTableModel tableModel = new DefaultTableModel();


    tableModel.addColumn("Sale ID");
    tableModel.addColumn("Total");

    ArrayList<Sale> salesMadeByClient = saleManager.findSalesByClientID(clientID);

    for (Sale sale : salesMadeByClient) {
        Object[] rowData = {
            sale.getSaleID(),   
            sale.getTotal()    
        };
        

        tableModel.addRow(rowData);
    }

    clientPurchasesJTable.setModel(tableModel);
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientPurchasesJTable;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel editItemHeader;
    private javax.swing.JTextField enterNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton loyaltyStatusButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton saleContentsButton;
    private javax.swing.JSpinner totalSpentJSpinner;
    // End of variables declaration//GEN-END:variables
}
