/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.Client;
import Backend.Part;
import Backend.Sale;
import Backend.clientManager;
import Backend.inventoryManager;
import Backend.saleManager;
import DBMS.DB;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dazzl
 */
public class saleEditor extends javax.swing.JFrame {

    // The global variables that are required for fulling in the data on this screen.
    private Part part;
    private inventoryManager manager;

    /**
     * Creates new form editPanel
     */
    //Building site
    public saleEditor(int inSID) {
        initComponents();
        
        // This method populates the UI components with the data from the class
        populateFields(inSID);
        populatePartsTable(inSID);
        
        // Disposes the screen on close but not the whole prgram
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Populates the combo box with the correct fields which can be selected for a part

        
        //Places the screen in the middle of the users display
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editItemHeader = new javax.swing.JLabel();
        saleIDTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalSpentJSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        saleContentsTABLE = new javax.swing.JTable();
        clientNameDisplayField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editItemHeader.setFont(new java.awt.Font("Candara Light", 0, 48)); // NOI18N
        editItemHeader.setText("SALE DETAILS");

        saleIDTextField.setEditable(false);
        saleIDTextField.setText("Enter your sale ID");
        saleIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleIDTextFieldActionPerformed(evt);
            }
        });

        confirmButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setText("Total Spent:");

        saleContentsTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(saleContentsTABLE);

        clientNameDisplayField.setEditable(false);
        clientNameDisplayField.setText("Enter your client ID");

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("SALE ID:");

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setText("CLIENT ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientNameDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(editItemHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(totalSpentJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(editItemHeader)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(totalSpentJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    // Enetering the name of the part
    private void saleIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleIDTextFieldActionPerformed

    }//GEN-LAST:event_saleIDTextFieldActionPerformed
    
    // The metod which fills in the data of the UI components
        private void populateFields(int inSaleID) {
            saleManager sManager = new saleManager();
            Sale s = sManager.findSaleBySaleID(inSaleID);
            clientManager cManager = new clientManager();
            Client c = cManager.findClientById(s.getClientId());
          
            saleIDTextField.setText(s.getSaleID() + "");
            clientNameDisplayField.setText(c.getName()+ "");
            
            
            totalSpentJSpinner.setValue(s.getTotal());
            
            
            
            
        }
            
 private void populatePartsTable(int inSID) {

    saleManager manager = new saleManager();

    DefaultTableModel tableModel = new DefaultTableModel();
   

    tableModel.addColumn("Part ID");
    tableModel.addColumn("Part Name");
    tableModel.addColumn("Price");
    tableModel.addColumn("QTY");

    Sale s = manager.findSaleBySaleID(inSID);
    ArrayList<Part> partsInSale = s.getSales();
    ArrayList<Integer> quanityOfParts = s.getQuantities();
    int i = 0;
    
    for (Part part : partsInSale) {
        Object[] rowData = {
            part.getPartID(),   
            part.getName(),
            part.getPrice(),
            quanityOfParts.get(i),
            i++
            
                
        };
        

        tableModel.addRow(rowData);
    }
    
    saleContentsTABLE.setModel(tableModel);
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientNameDisplayField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel editItemHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable saleContentsTABLE;
    private javax.swing.JTextField saleIDTextField;
    private javax.swing.JSpinner totalSpentJSpinner;
    // End of variables declaration//GEN-END:variables
}
